### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by DELL150150** [akhi07rx/File-Uploader-for-Google-Drive#1]
I am new to github , sorry if this isn't the place for it
So, I was getting this error after putting in the link,I have tried this with 2 accounts 

An error occurred: [Errno 21] Is a directory: '/content/drive/MyDrive/Downloads/

thanks

**Comment by akhi07rx** [comment]
This issue could happen if the file_name is empty. Make sure that you're providing a valid file name and path when using the function.
